postgres:
    image: postgres:11.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - /tmp/odoo/postgres:/var/lib/postgresql/data

odoo:
    image: elicocorp/odoo:12.0
    command: start
    ports:
      - 8069:8069
    links:
      - postgres:db
    environment:
      - ODOO_DB_USER=odoo
      - ODOO_DB_PASSWORD=odoo
      - ODOO_ADMIN_PASSWD=admin
    volumes:
      - /tmp/odoo/filestore:/opt/odoo/data/filestore
      - /tmp/odoo/sessions:/opt/odoo/data/sessions